README.md
Here is some initial information for the README. I made an assumption about deployment using travis ci which may or may not be true so please confirm and provide me with the right information.
Also, if we are planning to have some kind if database backing this app that will need creation and initialization, we can add that information to the README as well.
=> Adds info to README

.scss-lint.yml, Gemfile, Gemfile.lock, Rakefile
=> Add scss_lint and hook up to build.

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/checkouts_controller.rb, app/controllers/fines_controller.rb, app/controllers/requests_controller.rb, app/views/checkouts/index.html.erb, app/views/fines/index.html.erb, app/views/requests/index.html.erb, app/views/shared/_navigation.html.erb, app/views/summaries/index.html.erb, config/routes.rb, spec/features/navigation_spec.rb
=> Initial page scaffold

config/application.rb
Closes #17 
Waiting on short names list (that doesn't currently exist in any of our apps)
=> Add a library code/translation configuration.

app/views/layouts/application.html.erb
Used the one Bootstrap 4 suggests. Fixes #56
=> Add needed meta tags

app/controllers/application_controller.rb, app/controllers/checkouts_controller.rb, app/models/checkout.rb, app/services/symphony_client.rb, app/views/checkouts/index.html.erb, config/application.rb, spec/controllers/checkouts_controller_spec.rb, spec/features/navigation_spec.rb, spec/models/checkout_spec.rb
=> Adds checkouts tab

app/controllers/sessions_controller.rb, config/initializers/warden.rb, spec/controllers/sessions_controller_spec.rb
=> Trigger shibboleth sso logout after logging out of the application

app/models/checkout.rb, app/views/checkouts/index.html.erb, config/settings.yml, spec/models/checkout_spec.rb
=> Adds View in SearchWorks link to checkouts.

app/helpers/application_helper.rb, app/models/checkout.rb, app/views/checkouts/_checkout.html.erb, app/views/checkouts/index.html.erb, spec/features/checkouts_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/checkout_spec.rb
=> Extract a checkouts partial and group recalls separate from other checkouts

app/assets/stylesheets/modules/top_navbar.scss, app/views/shared/_header_navbar.html.erb
=> Remove navbar toggler

app/services/symphony_client.rb, config/initializers/symphony_logging.rb
Resulting in:
```
Started GET "/checkouts" for 127.0.0.1 at 2019-07-12 07:14:49 -0700
Processing by CheckoutsController#index as HTML
[HTTP] > POST https://symws-dev.stanford.edu/symws/user/staff/login
[HTTP] < 200 OK application/json (158.291ms)
[HTTP] > GET https://symws-dev.stanford.edu/symws/user/patron/key/....?includeFields=%2A%2CcircRecordList%7B%2A%2Citem%7B%2A%2Cbib%7Btitle%2Cauthor%7D%2Ccall%7BsortCallNumber%2CdispCallNumber%7D%7D%7D
[HTTP] < 200 OK application/json (1085.114ms)
Rendering checkouts/index.html.erb within layouts/application
Rendered shared/_navigation.html.erb (0.8ms)
Rendered collection of checkouts/_checkout.html.er.[...]
```
=> Add request notifications + logging for symphony API calls

app/assets/stylesheets/modules/navigation.scss, app/assets/stylesheets/sul-variables.scss, app/views/shared/_navigation.html.erb
=> Style the main nav a little closer to the designs

app/controllers/requests_controller.rb, app/models/request.rb, app/services/symphony_client.rb, app/views/requests/index.html.erb, spec/controllers/requests_controller_spec.rb, spec/features/navigation_spec.rb, spec/models/request_spec.rb, spec/services/symphony_client_spec.rb
=> Retrieve request/hold data from Symphony and poke it through the requests controller

app/controllers/fines_controller.rb, app/models/fine.rb, app/services/symphony_client.rb, app/views/fines/_fine.html.erb, app/views/fines/_fine.json.jbuilder, app/views/fines/index.html.erb, app/views/fines/index.json.jbuilder, spec/controllers/fines_controller_spec.rb, spec/features/navigation_spec.rb, spec/models/fine_spec.rb, spec/services/symphony_client_spec.rb
=> Add fines API request and pass the data through to the fines controller

app/controllers/summaries_controller.rb, app/models/patron.rb, app/views/summaries/index.html.erb, spec/controllers/summaries_controller_spec.rb, spec/features/navigation_spec.rb, spec/models/patron_spec.rb, spec/support/fixtures/patron/521181.json
Part of #53
Next steps are separating patron types (SUNetID, fee borrower, etc.).
Paired with Camille and Tony on this PR.
=> Adds patron status and expiration logic

app/assets/stylesheets/base.scss, app/assets/stylesheets/bootstrap-variables.scss, app/assets/stylesheets/sul-variables.scss, app/views/checkouts/_checkout.html.erb, spec/features/checkouts_spec.rb
=> Add checkouts status

app/models/patron.rb, app/views/summaries/index.html.erb, spec/features/navigation_spec.rb, spec/features/summaries_spec.rb, spec/models/patron_spec.rb
=> Adds fee borrower.

app/views/checkouts/_checkout.html.erb
=> Get the Searchworks link to align with the rest of the expanded data

app/assets/javascripts/listSort.js, app/assets/stylesheets/base.scss, app/assets/stylesheets/sul-variables.scss, app/controllers/requests_controller.rb, app/models/request.rb, app/views/requests/_request.html.erb, app/views/requests/index.html.erb, spec/controllers/requests_controller_spec.rb, spec/features/requests_spec.rb, spec/support/fixtures/patron/521182.json
This PR also generalizes `checkouts.js` -> `listSort.js` so it can be used in multiple places.
=> Add information to requests tab fixes #50

app/helpers/application_helper.rb, app/views/checkouts/_checkout.html.erb, app/views/fines/_fine.html.erb, app/views/requests/_request.html.erb, spec/helpers/application_helper_spec.rb
This also abstracts this out into a helper since it's used in three places ¯\\_(ツ)_/¯
=> Fix SW Link Alignment on Requests Page

app/assets/stylesheets/base.scss, app/assets/stylesheets/sul-variables.scss
=> Add a background-color to the body.

app/controllers/application_controller.rb, app/controllers/reset_pins_controller.rb, app/services/symphony_client.rb, app/views/reset_pins/index.html.erb, app/views/sessions/form.html.erb, app/views/sessions/index.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/reset_pins_controller_spec.rb, spec/features/reset_pin_spec.rb, spec/support/fake_symphony.rb
```
Stanford University Libraries PIN Change request
Please follow this link to CHANGE YOUR PIN.
If you have any questions or you are unable to change your PIN, please contact Green Library Privileges at 
Thank you,
Library Privileges Division
Stanford University Libraries
```
=> Setup reset/request PIN pages and workflow fixes #47

app/models/patron.rb, app/services/symphony_client.rb, app/views/summaries/index.html.erb, spec/models/patron_spec.rb
=> Get borrow limit from symphony and render it in the summaries page 

app/models/fine.rb, app/views/fines/_fine.html.erb, spec/features/fines_spec.rb, spec/models/fine_spec.rb
=> Add a nice translated status to fine / bill reasons fixes #155

app/controllers/fines_controller.rb, app/models/checkout.rb, app/views/fines/index.html.erb, spec/controllers/fines_controller_spec.rb, spec/features/fines_spec.rb, spec/models/checkout_spec.rb
=> Add accrued fines (not yet payable) to the fines page fixes #140

app/views/checkouts/_checkout.html.erb, spec/features/checkouts_spec.rb
=> Add fines accrued information to checkout page fixes #163

app/models/patron.rb, app/services/symphony_client.rb, spec/models/patron_spec.rb
Fixes #143
Paired with Jack on code, Chris on specs.
=> Add patron methods to distinguish sponsors and proxy borrowers

app/assets/stylesheets/base.scss, app/assets/stylesheets/bootstrap-variables.scss, app/assets/stylesheets/sul-variables.scss
=> Minor color fixes #179

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/checkouts.scss, app/controllers/renewals_controller.rb, app/models/checkout.rb, app/services/symphony_client.rb, app/views/checkouts/_checkout.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/renewals_controller_spec.rb, spec/features/checkouts_spec.rb, spec/features/renew_item_spec.rb, spec/models/checkout_spec.rb, spec/support/fake_symphony.rb, spec/support/fixtures/patron/521181.json
Fixes #48 
I reviewed the design and styling prior to marking as ready w/ @jvine
=> Add renew one item button

app/assets/javascripts/contact_form.js, app/views/shared/contact_forms/_form.html.erb
=> Update contact form for HTML + a11y fixes #167

app/models/checkout.rb, app/views/checkouts/_checkout.html.erb, spec/features/checkouts_spec.rb, spec/models/checkout_spec.rb
=> Add "Days overdue" to overdue checkouts

app/views/shared/contact_forms/_form.html.erb
Fixes #193; I looked briefly into incorporating HTML validation into our rspec tests, but there's not a clear way to do it, so 🤷‍♂
=> Use unique IDs for contact form fields

app/views/shared/_header_navbar.html.erb
=> Adds consistent margin to links/buttons fixes #197

.rubocop.yml, app/controllers/checkouts_controller.rb, app/controllers/fines_controller.rb, app/controllers/requests_controller.rb, app/models/patron.rb, app/services/symphony_client.rb, app/views/shared/_navigation.html.erb, app/views/summaries/index.json.jbuilder, spec/controllers/checkouts_controller_spec.rb, spec/controllers/fines_controller_spec.rb, spec/controllers/requests_controller_spec.rb, spec/features/proxy_user_spec.rb, spec/models/patron_spec.rb, spec/support/fixtures/patron/521197.json
Part of #159 
- [~] ~deal with Patron model class length (too long!)~
- [~] add borrower name to group tab (put at top of expanded list item) for sponsor and proxies
- [~] styling around tab controls
- [~] display counts in the tabs (split this out to new ticket probably)
=> Adds group checkouts, requests, and fines

app/assets/stylesheets/modules/icons.scss, app/assets/stylesheets/modules/navigation.scss, app/models/checkout.rb, app/views/shared/_navigation.html.erb, app/views/summaries/index.html.erb, spec/features/checkouts_spec.rb, spec/features/contact_form_spec.rb, spec/features/feedback_form_spec.rb, spec/features/fines_spec.rb, spec/features/navigation_spec.rb, spec/features/summaries_spec.rb, spec/support/fixtures/patron/521181.json, spec/support/fixtures/patron/521182.json
=> Add navigation and summary statuses

app/views/checkouts/_checkout.html.erb
=> Add claim text in details; fixes #218

app/views/shared/_flash_msg.html.erb, spec/views/shared/flash_msg.html.erb_spec.rb
=> Allow multiple flash messages of a given type

Gemfile, Gemfile.lock, app/assets/stylesheets/modules/record.scss, app/controllers/application_controller.rb, app/controllers/fines_controller.rb, app/models/patron.rb, app/models/payment.rb, app/services/symphony_legacy_client.rb, app/views/fines/_payment.html.erb, app/views/fines/index.html.erb, config/settings/test.yml, spec/controllers/fines_controller_spec.rb, spec/features/fines_spec.rb, spec/features/navigation_spec.rb, spec/models/payment_spec.rb, spec/services/symphony_legacy_client_spec.rb, spec/support/fake_symphony.rb, spec/support/fixtures/patron/521181.json, spec/support/fixtures/patron/521182.json, spec/support/fixtures/patron/payment_history/999181.xml, spec/support/fixtures/patron/payment_history/999182.xml
Full view:
Responsive view:
Lists item showing truncation with ellipses after two lines:
=> Adds payment history using symphony legacy ws client

app/assets/stylesheets/modules/navigation.scss, app/views/shared/_navigation.html.erb
=> Update nav tab styling to avoid ugly wrapping; fixes #221

app/models/patron.rb, app/views/summaries/index.html.erb, spec/models/patron_spec.rb, spec/views/summaries/index.html.erb_spec.rb
I guess this closes #236 but I couldn't reproduce it w/ a particular user.
=> Handle nil expired date

app/assets/stylesheets/base.scss, app/assets/stylesheets/sul-variables.scss, app/views/checkouts/_checkout.html.erb, app/views/fines/_fine.html.erb, app/views/requests/_request.html.erb
=> Address color contrast issues; fixes #244

app/models/checkout.rb, spec/models/checkout_spec.rb
=> Add unseenRenewablesCheck as part of Checkout renewable? logic

app/assets/stylesheets/base.scss, app/models/patron.rb, app/views/patron/_patron.html.erb, app/views/shared/_navigation.html.erb, spec/features/navigation_spec.rb, spec/models/patron_spec.rb, spec/views/summaries/index.html.erb_spec.rb
=> Translate "Contact us" for BARRED status

app/assets/stylesheets/bootstrap-variables.scss, app/assets/stylesheets/modules/header_navbar.scss, app/assets/stylesheets/modules/record.scss, app/assets/stylesheets/modules/top_navbar.scss, app/helpers/checkouts_helper.rb, app/models/payment.rb, app/views/checkouts/_checkout.html.erb, app/views/fines/_fine.html.erb, app/views/fines/_payment.html.erb, app/views/fines/index.html.erb, app/views/group/_group.html.erb, app/views/patron/_patron.html.erb, app/views/requests/_request.html.erb, app/views/sessions/form.html.erb, app/views/sessions/index.html.erb, app/views/shared/_global_footer.html.erb, app/views/shared/_header_navbar.html.erb, app/views/shared/_navigation.html.erb, app/views/shared/feedback_forms/_form.html.erb, app/views/summaries/_summary.html.erb, spec/features/navigation_spec.rb, spec/features/proxy_user_spec.rb, spec/features/requests_spec.rb, spec/helpers/checkouts_helper_spec.rb, spec/models/payment_spec.rb
=> Design tweaks

app/assets/images/icons/renew.svg, app/assets/stylesheets/bootstrap-variables.scss, app/assets/stylesheets/modules/icons.scss, app/controllers/renewals_controller.rb, app/models/checkout.rb, app/services/symphony_client.rb, app/views/checkouts/index.html.erb, app/views/summaries/_summary.html.erb, config/routes.rb, spec/controllers/renewals_controller_spec.rb, spec/features/renew_item_spec.rb, spec/services/symphony_client_spec.rb
=> Add a button for renewing all eligible items

app/views/fines/_payment.html.erb
=> Use the same col layout on the payments detail as used elsewhere

app/assets/stylesheets/modules/sul-footer.scss, app/views/layouts/application.html.erb, app/views/shared/_global_footer.html.erb
=> Adapt the latest SU footer for our site; fixes #256

app/views/shared/_top_navbar.html.erb
=> Put the top navbar elements inside a container

app/assets/javascripts/analytics.js, app/views/checkouts/_checkout.html.erb, app/views/fines/_fine.html.erb, app/views/fines/_payment.html.erb, app/views/requests/_request.html.erb
Part of #260 , some of those items are blocked by inflight work.
=> Start adding custom analytics events

app/assets/javascripts/modal.js, app/controllers/requests_controller.rb, app/views/requests/_request.html.erb, app/views/requests/edit.html.erb
=> Move change/cancel request into a modal fixes #242

app/views/checkouts/index.html.erb, app/views/fines/index.html.erb, app/views/requests/index.html.erb, app/views/shared/_group_tabs.html.erb, app/views/shared/_navigation.html.erb, app/views/summaries/index.html.erb, spec/features/proxy_user_spec.rb, spec/views/checkouts/index.html.erb_spec.rb, spec/views/summaries/index.html.erb_spec.rb
Fixes #159 
The tabs now display a count or dollar value:
=> Adds values to self and group tabs.

app/models/group.rb, app/models/patron.rb, spec/models/group_spec.rb, spec/models/patron_spec.rb
=> Proxy borrowers now inherit group standing/status.

app/views/requests/index.html.erb
=> Add text to requests footer linking out to ILLIAD scan requests

app/assets/stylesheets/base.scss, app/assets/stylesheets/bootstrap-variables.scss, app/assets/stylesheets/mixins.scss
=> Remove explicit color styling in favor of global bootstrap variable

app/assets/javascripts/convertButton.js, app/assets/javascripts/modal.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/requests.scss, app/views/requests/_request.html.erb, app/views/requests/edit.html.erb
=> Fixes #316 by doing style updates and js plugin

app/models/request.rb, app/services/symphony_client.rb, spec/models/request_spec.rb, spec/support/fixtures/patron/521181.json, spec/support/fixtures/patron/521182.json, spec/support/fixtures/patron/521197.json
Holds for things that have e.g. ONORDER items don't have item information yet.
=>  Use the bib record for requests instead of the item/bib

app/views/checkouts/_policies.html.erb, app/views/checkouts/_recalled.html.erb, app/views/checkouts/index.html.erb, app/views/fines/index.html.erb, app/views/requests/index.html.erb, spec/features/checkouts_spec.rb, spec/features/fines_spec.rb, spec/features/requests_spec.rb, spec/support/fixtures/patron/521206.json, spec/views/checkouts/index.html.erb_spec.rb
Fixes #267 
Paired with @camillevilla
=> Cleaner views for users without fines, requests, or checkouts

app/models/patron.rb, app/views/patron/_expired.html.erb, app/views/patron/_fee_borrower.html.erb, app/views/patron/_patron.html.erb, spec/models/patron_spec.rb, spec/views/patron/_expired.html.erb_spec.rb, spec/views/patron/_fee_borrower.html.erb_spec.rb, spec/views/patron/_patron.html.erb_spec.rb, spec/views/summaries/index.html.erb_spec.rb
=> Display appropriate values for various pieces of patron data for expired users

app/views/patron/_expired.html.erb, app/views/patron/_fee_borrower.html.erb, app/views/patron/_patron.html.erb
=> Fix regression from #259

app/views/checkouts/_checkout.html.erb, app/views/fines/_fine.html.erb, app/views/fines/_payment.html.erb, app/views/requests/_request.html.erb
=> Make item rows expandable by clicking anywhere on the row

app/views/fines/index.html.erb
I accidentally moved the `ul` into the `div` upon rebase...
=> Fix misplacement of payment list item

app/controllers/payments_controller.rb, config/locales/en.yml, spec/controllers/payments_controller_spec.rb
=> Change payment cancelled flash message

app/controllers/renewals_controller.rb, app/services/symphony_client.rb, app/views/shared/_flash_msg.html.erb, config/locales/en.yml, spec/controllers/renewals_controller_spec.rb, spec/services/symphony_client_spec.rb
=> Update flash message for bulk renewals

config/settings.yml
=> Add placeholder configuration so the payments link can be created

app/views/fines/index.html.erb
=> Add margin class to pay button fixes #357

app/controllers/fines_controller.rb, app/models/payment.rb, spec/controllers/fines_controller_spec.rb, spec/models/payment_spec.rb
=> Sort the fines in reverse date order (newest first).

config/locales/en.yml, spec/controllers/payments_controller_spec.rb
=> Update payment history success flash message.

app/views/shared/_group_tabs.html.erb
=> Add padding and margin fixes #354

app/controllers/sessions_controller.rb, app/views/sessions/index.html.erb, spec/controllers/sessions_controller_spec.rb, spec/features/navigation_spec.rb, spec/views/sessions/index.html.erb_spec.rb
=> Add maintenance information when Symphony is down; fixes #298

app/models/payment.rb, spec/models/payment_spec.rb
=> Fix bug where fine payment incorrectly shows Paid

app/controllers/sessions_controller.rb, config/settings.yml
=> Add a home page banner message

app/assets/javascripts/analytics.js, app/views/shared/contact_forms/_form.html.erb
Gets #260 almost there... waiting on one piece of clarification about fines.
=> Adds additional analytics events

app/models/patron.rb
=> Remove Research group sponsor

app/helpers/application_helper.rb, app/views/sessions/form.html.erb, app/views/sessions/index.html.erb, spec/helpers/application_helper_spec.rb
=> Correct login text on pin login page

app/assets/javascripts/listSort.js, app/models/payment.rb, app/views/fines/_payment.html.erb, app/views/fines/index.html.erb, spec/features/fines_spec.rb, spec/support/fixtures/patron/payment_history/999181.xml
=> Allow Payments History to sort when sort option is chosen

app/views/checkouts/_checkout.html.erb, app/views/checkouts/_recalled.html.erb, app/views/checkouts/index.html.erb, app/views/fines/_fine.html.erb, app/views/fines/index.html.erb, app/views/requests/_borrow_direct_request.html.erb, app/views/requests/_request.html.erb, app/views/requests/index.html.erb
Fixes #270
🍐'd with Tony and Jessie on this.
=> Revisit responsive layout

app/models/checkout.rb, spec/models/checkout_spec.rb
=> Recalled checkouts refer to their recall due date

app/views/fines/index.html.erb
=> Refer to 'proxy' fines, not group fines

app/assets/stylesheets/modules/record.scss
=> Add color indicator to expand/collapse buttons

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/skip_link.scss, app/assets/stylesheets/sul-variables.scss, app/views/layouts/application.html.erb
=> Add 'skip to' link; fixes #415

app/assets/javascripts/ajax_in_place_updates.js, app/assets/javascripts/application.js, app/assets/javascripts/listSort.js, app/controllers/application_controller.rb, app/controllers/fines_controller.rb, app/controllers/payments_controller.rb, app/services/symphony_legacy_client.rb, app/views/fines/index.html.erb, app/views/payments/index.html.erb, config/routes.rb, spec/controllers/fines_controller_spec.rb, spec/controllers/payments_controller_spec.rb, spec/features/fines_spec.rb, spec/services/symphony_legacy_client_spec.rb
=> Allow payment history to load async on a button click

.travis.yml, Gemfile, Gemfile.lock, README.md, app/models/group.rb, app/models/patron.rb, app/services/symphony_db_client.rb, spec/features/proxy_user_spec.rb, spec/models/group_spec.rb, spec/models/patron_spec.rb, spec/support/fixtures/patron/521197.json
Fixes #261 
Fixes #386 
Adds Oracle DB connection class to get group circrecord keys.
Requires connection information from https://github.com/sul-dlss/shared_configs/tree/mylibrary-dev to retrieve data for sponsors; if you don't care, the connection information is unnecessary to the rest of the application.
=> Adds Oracle queries for differentiating group activity

app/views/fines/index.html.erb, app/views/payments/index.html.erb, spec/features/fines_spec.rb
=> Change 'Payment History' to 'History', fixes #420

app/assets/javascripts/nav_spinners.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/nav_spinner.scss
=> Add a loading spinner to our main nav; fixes #378

.rubocop.yml, app/models/payment.rb, app/views/fines/_payment.html.erb, spec/features/fines_spec.rb, spec/models/payment_spec.rb, spec/support/fixtures/patron/payment_history/999181.xml, spec/support/fixtures/patron/payment_history/999182.xml
=> Render correct bill reasons

app/services/symphony_db_client.rb, config/initializers/okcomputer.rb
=> Add an okcomputer check to ping the symphony oracle database

app/views/patron/_expired.html.erb, app/views/patron/_fee_borrower.html.erb, app/views/patron/_patron.html.erb
=> Prevent patron info labels from wrapping

app/views/summaries/_summary.html.erb, spec/features/proxy_user_spec.rb, spec/features/sponsor_user_spec.rb, spec/support/fixtures/patron/521187.json
=> Replaces pay all button with explanation text for group tab

config/settings.yml
=> Add blog post link to welcome flash message

app/models/concerns/bib_record.rb, app/views/checkouts/_checkout.html.erb, app/views/checkouts/_checkout.json.jbuilder, app/views/fines/_fine.html.erb, app/views/fines/_fine.json.jbuilder, spec/features/checkouts_spec.rb, spec/features/fines_spec.rb, spec/models/checkout_spec.rb, spec/models/fine_spec.rb, spec/views/checkouts/_checkout.html.erb_spec.rb
=> Add barcode to checkouts and fines; fixes #458

Capfile, config/deploy/prod.rb
Reverts sul-dlss/mylibrary#449
=> Revert "Report deploys to newrelic"

README.md
Thought this might be nice if folks run across this project in GitHub and / or we want a quick shortcut to JIRA. ¯\\_(ツ)_/¯
See: sul-dlss/operations-tasks#2011
=> Add a reference to MyLibrary JIRA queue

app/models/checkout.rb, spec/models/checkout_spec.rb
if field is nil so checkouts list can display.
=> Display generic library name

config/settings.yml
@saseestone Let us know when you'd like the flash message to be removed.
=> Removes flash message announcing new My Library Account.

config/application.rb, spec/helpers/requests_helper_spec.rb, spec/models/library_location_spec.rb
=> Add SRWC to pickup libraries

config/settings.yml
=> Enable global alert and update it for COVID-19 updates.

config/settings.yml, spec/models/checkout_spec.rb
=> Update global alert text w/ messaging about request service.

config/settings.yml
=> Update covid alert

config/settings.yml
=> Update COVID banner

app/assets/stylesheets/modules/scheduling.scss, app/views/schedules/show.html.erb, app/views/shared/_modal.html.erb
=> Make modals XL (and move schedule once cancel button to the left)

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/scheduling.scss, app/controllers/schedules_controller.rb, app/helpers/summaries_helper.rb, app/models/patron.rb, app/services/symphony_client.rb, app/views/group/_group.html.erb, app/views/patron/_expired.html.erb, app/views/patron/_fee_borrower.html.erb, app/views/patron/_patron.html.erb, app/views/requests/index.html.erb, app/views/schedules/show.html.erb, app/views/shared/_modal.html.erb, app/views/summaries/_summary.html.erb, app/views/summaries/index.html.erb, config/application.rb, config/initializers/content_security_policy.rb, config/routes.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, spec/features/requests_spec.rb, spec/features/summaries_spec.rb, spec/helpers/summaries_helper_spec.rb, spec/models/patron_spec.rb, spec/views/summaries/index.html.erb_spec.rb
=> Add a button to schedule visits to Green & SPEC

app/views/summaries/index.html.erb
=> Wrap link in a div

app/assets/stylesheets/modules/scheduling.scss, app/controllers/schedules_controller.rb, app/helpers/summaries_helper.rb, app/models/patron.rb, app/views/requests/index.html.erb, app/views/schedules/_schedule_library_pickup_dropdown.html.erb, app/views/schedules/_schedule_library_visit_dropdown.html.erb, app/views/schedules/business_pickup.html.erb, app/views/schedules/show.html.erb, app/views/summaries/_summary.html.erb, config/routes.rb, config/settings.yml, config/settings/test.yml, spec/features/requests_spec.rb, spec/features/summaries_spec.rb, spec/helpers/summaries_helper_spec.rb, spec/views/summaries/index.html.erb_spec.rb
=> Add Pickup Scheduling Support for GSB (via LibCal embed)

app/helpers/summaries_helper.rb, config/routes.rb, config/settings.yml, config/settings/test.yml
=> Add EAST-ASIA library pickup support.

app/models/patron.rb, spec/models/patron_spec.rb
=> Don't allow expired users to schedule visits or pickups.

app/helpers/summaries_helper.rb, app/models/patron.rb, app/views/requests/index.html.erb, app/views/summaries/_summary.html.erb, app/views/summaries/index.html.erb, config/settings.yml, config/settings/test.yml, spec/helpers/summaries_helper_spec.rb, spec/models/patron_spec.rb, spec/views/summaries/index.html.erb_spec.rb
Shared configs PRs coming soon
Closes #590
=> Enable staff to schedule visits

app/views/schedules/business_pickup.html.erb, app/views/schedules/show.html.erb
per @jvine (based on user feedback)
=> Make the scheduling modals 900px tall.

app/models/request.rb, app/views/summaries/_summary.html.erb, spec/features/requests_spec.rb, spec/features/summaries_spec.rb
=> Change button(s) to request pickup appointments on summaries page to be a link

app/helpers/summaries_helper.rb, config/application.rb, config/routes.rb, config/settings.yml, config/settings/test.yml
This PR also adds scheduling for Hopkins/Miller since that's being enabled for pickup
For release Sept. 28
=> Update pickup library configurations to match sul-dlss/sul-requests#1076

app/views/requests/_request.html.erb
=> Always use requests to cancel CDL requests

app/controllers/schedules_controller.rb, app/helpers/summaries_helper.rb, app/views/schedules/business_pickup.html.erb, app/views/schedules/libcal_pickup.html.erb, config/application.rb, config/routes.rb, config/settings.yml, config/settings/test.yml
=> Add a Pickup Scheduling Option for LAW

config/settings.yml
=> Remove defunct global alert HTML

config/initializers/global_alerts.rb
Part of sul-dlss/global_alerts#12
=> Explicitly set Global Alerts application name

app/models/checkout.rb, app/models/request.rb, app/views/checkouts/_cdl_checkout.html.erb, app/views/checkouts/_checkout.html.erb, app/views/requests/_request.html.erb, config/application.rb, config/settings.yml, spec/models/checkout_spec.rb, spec/models/request_spec.rb, spec/views/checkouts/_checkout.html.erb_spec.rb, spec/views/requests/_request.html.erb_spec.rb
=> Use a separate library code for BorrowDirect ILL vs ILLiad ILB

config/application.rb
=> Update email address used for BUSINESS

app/views/shared/feedback_forms/_form.html.erb, app/views/shared/feedback_forms/_reporting_from.html.erb, spec/features/internal_flash_message_spec.rb
Borrows layout from SearchWorks, see:
https://github.com/sul-dlss/SearchWorks/pull/2660
=> Update layout of feedback form (#571)

app/views/requests/index.html.erb, app/views/shared/_schedule_links.html.erb, config/locales/en.yml, config/settings.yml
=> Show scheduling false_message when scheduling is turned off.

app/views/requests/index.html.erb
=> Add information about Aeon to requests tab

app/assets/javascripts/analytics.js, app/views/layouts/application.html.erb, config/settings.yml
=> Migrate analytics to GA4

app/services/folio_client.rb
=> Change the pickup expiration time of a request

.rubocop.yml, .rubocop_todo.yml, app/helpers/application_helper.rb, app/models/concerns/folio/folio_record.rb, app/models/folio/checkout.rb, app/models/folio/fine.rb, app/models/folio/patron.rb, app/models/folio/request.rb, app/models/folio/service_point.rb, app/services/folio_client.rb, app/services/folio_graphql_client.rb, app/views/summaries/index.html.erb, config/initializers/ils_logging.rb, config/initializers/warden.rb, config/service-points.json, config/settings.yml
Fixes https://github.com/sul-dlss/mylibrary/issues/808
Replaces #741
=> Stub out some FOLIO client work (from #741)

app/services/folio_client.rb
=> Add API methods for assigning and validating a user pin

Jenkinsfile
It looks like this was forgotten when we did #653
=> Update the main branch name

app/models/folio/fine.rb, app/models/folio/patron.rb, app/services/folio_graphql_client.rb
=> Map data from accounts to fines; charges seems to miss a lot

app/controllers/requests_controller.rb, app/models/folio/patron.rb, app/models/folio/request.rb, app/models/folio/service_point.rb, app/services/folio_client.rb, app/services/folio_graphql_client.rb, app/services/symphony_client.rb, spec/controllers/requests_controller_spec.rb
Includes #826 for mapping information from the hold request
Replaces #802; using mod-patron's methods seems desirable (maybe they'll fix the required response body some day...)
Fixes #736
=> Wire up the cancel request button

app/services/folio_graphql_client.rb
This was broken before as session token is not defined in this class
I falsely thought my local setup was not working as a result
=> Fix FolioGraphqlClient ping method

app/controllers/renewals_controller.rb, app/models/concerns/folio/folio_record.rb, app/models/folio/request.rb, app/services/folio_client.rb, app/services/symphony_client.rb, spec/controllers/renewals_controller_spec.rb
=> Wire up renewals for FOLIO

app/models/folio/checkout.rb, app/services/folio_graphql_client.rb
=> Set renewals counts for FOLIO

app/models/folio/checkout.rb, app/services/folio_graphql_client.rb
=> Handle unlimited renewals policy

app/models/folio/checkout.rb, app/services/folio_graphql_client.rb
=> Get library_key (code) for checkouts from FOLIO

app/models/folio/checkout.rb, app/services/folio_graphql_client.rb
=> Check whether a checkout is on reserve

app/models/folio/request.rb, app/services/folio_graphql_client.rb
Made possible by https://github.com/sul-dlss/folio-graphql/pull/79
Part of https://github.com/sul-dlss/mylibrary/issues/827
=> Add queueTotalLength to patron request query in GraphQL

app/models/folio/patron.rb, app/services/folio_graphql_client.rb
Part of https://github.com/sul-dlss/mylibrary/issues/827
=> Populate patron borrowing limit

app/models/folio/checkout.rb, spec/models/folio/checkout_spec.rb
=> Implement Checkout#from_borrow_direct? for FOLIO

app/services/folio_graphql_client.rb
=> Get effectiveLocation code for holds

config/application.rb
=> Add new location PAGE-FC

app/models/folio/patron.rb
This fixes the broken reset PIN issue as far as my testing goes.
@thatbudakguy I was able to avoid changing anything about the encryption for now. If we are worried about it, we can address in a separate PR. I couldn't reproduce the issues around spaces and + that we saw. + seemed to be OK.
=> Change patron.key method to use user_info 

.rubocop.yml, Gemfile, Gemfile.lock, app/models/folio/checkout.rb, app/models/folio/group.rb, app/models/folio/patron.rb, app/models/folio/request.rb, app/services/folio_graphql_client.rb, spec/factories/patrons.rb, spec/models/folio/group_spec.rb, spec/models/folio/patron_spec.rb, spec/models/folio/request_spec.rb, spec/rails_helper.rb, spec/views/requests/_request.html.erb_spec.rb
=> Display proxy activity for checkouts and requests

app/models/folio/request.rb, config/application.rb, config/settings.yml
Based on #833
Wanted to get this up while I was on the topic. However, I'm not sure of any current requests with this code to test with in the UI and will keep this as a draft until I test that.
=> Use location code to determine if a request is from BorrowDirect

app/models/folio/request.rb
I commented out the logic so we would have it as reference in the future but I could also just delete it.
Part of #827
=> Stub out CDL logic for FOLIO Request model

app/models/folio/checkout.rb, app/models/folio/request.rb, config/application.rb, spec/models/folio/checkout_spec.rb, spec/models/folio/request_spec.rb
=> Implement Folio::Checkout and Folio::Request from_ilb? using placeholder location code

spec/rails_helper.rb
see https://github.com/sul-dlss/sul-requests/pull/1631
=> Pin required chromedriver version to v114

app/views/checkouts/_policies.html.erb, app/views/fines/index.html.erb, app/views/sessions/index.html.erb, app/views/summaries/index.html.erb
=> Update links for D9 website

config/initializers/config.rb
Needed to pick up e.g. https://github.com/sul-dlss/puppet/pull/9737
=> Read config values from the environment

app/models/concerns/folio/folio_record.rb, app/services/folio_graphql_client.rb, spec/models/concerns/folio/folio_record.rb, spec/models/folio/checkout_spec.rb, spec/models/folio/request_spec.rb
=> Fallback to holdingsRecord effectiveLocation for item without permanentLocation

app/helpers/requests_helper.rb, spec/helpers/requests_helper_spec.rb
After some late refactoring this got left out of my final PR for #905 by mistake
=> Exclude non-pickup service points from user dropdown

app/views/shared/_group_tabs.html.erb, spec/features/navigation_spec.rb, spec/features/proxy_user_spec.rb, spec/features/sponsor_user_spec.rb
Fixes #871
Proxy view
Sponsor view (same labels)
=> Change tab labels to reflect FOLIO proxy model

app/views/shared/_unavailable.html.erb
Requested by @saseestone -- see https://github.com/sul-dlss/global_alerts/issues/54
=> Change date on system unavailable page for FOLIO launch

app/controllers/application_controller.rb
=> Log-out old sessions that still have symphony patron keys

app/models/folio/patron.rb
Fixes https://github.com/sul-dlss/mylibrary/issues/933
=> Safely ask for patronGroup

app/services/folio_client.rb
=> Use mod-circulation to cancel requests because mod-patron cannot cancel title level holds

app/models/folio/patron.rb, spec/factories/patrons.rb, spec/models/folio/patron_spec.rb
- Safely search for patronGroup borrow limits
- Test Patron methods that involve the patronGroup
Fixes #938
=> Safely search for patronGroup borrow limits

app/models/folio/patron.rb, app/views/patron/_expired.html.erb, spec/models/folio/patron_spec.rb
=> A patron account is expired when not active

app/controllers/requests_controller.rb, app/services/folio_client.rb, config/settings.yml, spec/controllers/application_controller_spec.rb, spec/controllers/checkouts_controller_spec.rb, spec/controllers/contact_forms_controller_spec.rb, spec/controllers/feedback_forms_controller_spec.rb, spec/controllers/fines_controller_spec.rb, spec/controllers/payments_controller_spec.rb, spec/controllers/renewals_controller_spec.rb, spec/controllers/requests_controller_spec.rb, spec/controllers/reset_pins_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/summaries_controller_spec.rb, spec/factories/patrons.rb, spec/features/checkouts_spec.rb, spec/features/contact_form_spec.rb, spec/features/feedback_form_spec.rb, spec/features/fines_spec.rb, spec/features/internal_flash_message_spec.rb, spec/features/navigation_spec.rb, spec/features/payments_spec.rb, spec/features/proxy_user_spec.rb, spec/features/renew_item_spec.rb, spec/features/requests_spec.rb, spec/features/reset_pin_spec.rb, spec/features/sponsor_user_spec.rb, spec/features/summaries_spec.rb, spec/helpers/application_helper_spec.rb, spec/views/requests/_request.html.erb_spec.rb
Closes #956 and let's us start removing/refactoring Symphony-isms
=> Update tests for FOLIO

app/services/folio_client.rb
=> fix NameError: uninitialized constant FolioClient::Patron in FolioClient.pay_fines

app/models/folio/patron.rb
Fixes https://github.com/sul-dlss/mylibrary/issues/980
=> Patrons should not inherit status from their sponsors in FOLIO

app/models/folio/checkout.rb, app/models/folio/loan_policy.rb, app/models/folio/patron.rb, app/services/folio_client.rb, app/services/folio_graphql_client.rb, spec/factories/loan_policies.rb, spec/factories/patrons.rb, spec/features/checkouts_spec.rb, spec/features/navigation_spec.rb, spec/features/proxy_user_spec.rb, spec/features/renew_item_spec.rb, spec/features/sponsor_user_spec.rb, spec/features/summaries_spec.rb, spec/models/concerns/folio/folio_record.rb, spec/models/folio/checkout_spec.rb, spec/views/fines/index.html.erb_spec.rb
Fixes #961 
Example of record where loan policy has changed since checkout:
In prod:
With these changes:
=> Use current loan policy to evaluate renewability

app/models/illiad_requests.rb, spec/models/illiad_requests_spec.rb
What this pull request does:
- Provide handling for dates that are of the format 'mm/dd/yyyy' or 'm/d/yyyy' 
- Allow rescuing of any error that happens in parsing date/time
- If there is no "NotWantedAfter" field for non-scan types, also uses two months after creation date as the "not wanted after" display value
Closes #994
=> Handling 'NotWantedAfter' ILLIAD transaction values. 

app/services/folio_client.rb
This client uses Faraday instead of Http
=> Catch Faraday errors

app/models/folio/checkout.rb, app/models/folio/loan_policy.rb, app/services/folio_graphql_client.rb, config/folio/loan_policies.json, spec/factories/loan_policies.rb, spec/models/folio/loan_policy_spec.rb
Part of #1083 
I confirmed this prevents items with open holds from being requestable in mylibrary.
=> Check whether a hold is present that blocks renewal

app/views/fines/_pay_all_button.html.erb
=> Turn off turbo for payment form

config/initializers/content_security_policy.rb
This seems like an unintentional regression from #1025 ?
=> Restore CSP configs

README.md, config/initializers/warden.rb, spec/controllers/sessions_controller_spec.rb
=> move uid to remote_user

app/controllers/application_controller.rb
So that we have a standard way to lookup and instantiate patrons.
=> Use Folio::Patron.find to locate the user

app/javascript/listSort.js
=> Guard for cases where there is not a sortable list

app/assets/stylesheets/base.scss, app/assets/stylesheets/bootstrap-variables.scss, app/assets/stylesheets/modules/record.scss, app/assets/stylesheets/sul-variables.scss
=> clean up variables scss

app/views/checkouts/_policies.html.erb, app/views/sessions/index.html.erb, app/views/summaries/_summary.html.erb, app/views/summaries/index.html.erb, spec/features/summaries_spec.rb
based on the siteimprove extension.
=> site-improve accessibility improvements

app/mailers/contact_mailer.rb, app/views/contact_mailer/submit_feedback.text.erb, app/views/fines/_fine.html.erb, app/views/shared/contact_forms/_form.html.erb
=> add barcode/status to contact emails

app/views/shared/feedback_forms/_form.html.erb
=> auto add name/email for feedback form when logged in

app/models/folio/request.rb
Closes #1240?
Likely hitting this item method and not the one in the concern?
=> Default to an empty item rather than nil

app/models/folio/request.rb
`item` method already exists in `FolioRecord` https://github.com/sul-dlss/mylibrary/blob/main/app/models/concerns/folio/folio_record.rb#L47-L49
=> Remove duplicate method

app/services/folio_client.rb
Part of https://github.com/sul-dlss/sul-requests/issues/2673
The legacy barcode field seems much slower, but 🤷‍♂️
=> Also use the legacybarcode field for patron lookups

app/controllers/payments_controller.rb, app/models/cybersource/payment_request.rb, app/models/cybersource/payment_response.rb, app/views/fines/_pay_all_button.html.erb, spec/controllers/payments_controller_spec.rb, spec/models/cybersource/payment_request_spec.rb, spec/models/cybersource/payment_response_spec.rb, spec/views/fines/_pay_all_button.html.erb_spec.rb, spec/views/summaries/summary.html.erb_spec.rb
=> Send FOLIO account IDs through CyberSource for payment tracking
