- Gemfile
- Gemfile.lock
- app/services/symphony_client.rb
- config/initializers/okcomputer.rb
- config/settings.yml
- config/settings/test.yml
- spec/services/symphony_client_spec.rb
Fixes #13 
This is a very simple wrapper around the `HTTP` gem for connecting to symws. It uses data from `Settings` to make requests to the endpoint, and I've added a first action for requesting a session token and then reuse that session token to make additional requests. 
This pairs with https://github.com/sul-dlss/shared_configs/pull/972, which can also be used locally (as `config/settings/development.local.yml`) to test things out.
>  Add a simple HTTP client wrapper for connecting to symws

- app/helpers/application_helper.rb
- app/views/shared/_navigation.html.erb
- spec/features/navigation_spec.rb
- spec/helpers/application_helper_spec.rb
This follows the accessibility patterns described here: https://getbootstrap.com/docs/4.3/components/navs/#regarding-accessibility
The nav elements are tabbable <kbd>Tab</kbd> links that can be followed using <kbd>Enter</kbd>
> Adds in nav pills fixes #15

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/modules/top_navbar.scss
- app/controllers/application_controller.rb
- app/controllers/checkouts_controller.rb
- app/controllers/fines_controller.rb
- app/controllers/requests_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/summaries_controller.rb
- app/services/symphony_client.rb
- app/views/sessions/form.html.erb
- app/views/sessions/index.html.erb
- app/views/shared/_top_navbar.html.erb
- config/application.rb
- config/initializers/warden.rb
- config/routes.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/checkouts_controller_spec.rb
- spec/controllers/fines_controller_spec.rb
- spec/controllers/requests_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/controllers/summaries_controller_spec.rb
- spec/features/navigation_spec.rb
- spec/rails_helper.rb
- spec/services/symphony_client_spec.rb
Fixes #12 
This PR adds authentication workflows for sunetid + libraryid based login (and an extra stub auth strategy for mocking sunetid logins in development). 
Sunetid logins will go through shibboleth, get authenticated by the webserver, and then the result will come back to the application "magically". We then take the resulting user and look up their patron key in symphony.
Library ID logins get authenticated directly against the symphony user authentication API.
In development, you can run the rails server with the `REMOTE_USER` environment variable:
```
REMOTE_USER={your sunetid} be rails s
```
In all cases, we'll stash some enough user data in the current session using Warden so we can do authorization checks, and make additional requests to the symphony API.
Possible follow on …
> Perform user authentication and retrieve patron keys from symws

- app/assets/stylesheets/base.scss
- app/assets/stylesheets/bootstrap-variables.scss
- app/views/layouts/application.html.erb
- app/views/sessions/form.html.erb
- app/views/sessions/index.html.erb
Here's a smattering of style tweaks to make our implementation a little closer to the XD mockups.
Before:
After:
> Style tweaks

- app/views/shared/feedback_forms/_form.html.erb
- config/initializers/content_security_policy.rb
Define an application-wide content security policy, using the defaults provided by Rails. Our application is pretty simple, and the rules are fairly permissive by default, so this seems like a good opportunity to try it out.
For further information see the following documentation:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
> Enable the default Rails CSP

- app/assets/stylesheets/modules/record.scss
- app/views/checkouts/index.html.erb
- spec/features/checkouts_spec.rb
> Add responsive layout (at least mobile version) to checkouts tab

- app/views/checkouts/index.html.erb
- app/views/fines/index.html.erb
- app/views/layouts/application.html.erb
- app/views/requests/index.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_navigation.html.erb
- app/views/shared/_top_navbar.html.erb
- app/views/summaries/index.html.erb
- spec/features/navigation_spec.rb
> Reorganize application layout; fixes #79

- app/views/checkouts/_checkout.json.jbuilder
- app/views/checkouts/index.json.jbuilder
and include the original symphony response when in development.
If you visit e.g. http://127.0.0.1:3000/checkouts.json, you'll get something like:
This might be a useful development tool, if nothing else making it easier to see what's actually in the Symphony API response 🤷‍♂
> Add a JSON-API-ish representation of checkouts

- app/assets/stylesheets/base.scss
Turbolinks injects an inline `<style>` element, which doesn't play nice with the content security policies. Supposedly, there may be a way to whitelist it using a hash of its content, but I can't figure out how to make it work cross-browser. For now, we can just add the styles ourselves and ignore their styling entirely.
> Explicitly add turbolinks progress bar styles

- app/views/checkouts/index.html.erb
- app/views/fines/index.html.erb
- app/views/requests/index.html.erb
- app/views/summaries/index.html.erb
and also hide generic the `h1` except for screenreaders
> Update scaffolded pages to remove unneeded notice area 

- app/assets/stylesheets/base.scss
> Change the status svg stroke color to white for better contrast

- app/views/fines/_fine.html.erb
- app/views/fines/index.html.erb
- spec/features/fines_spec.rb
- spec/support/fixtures/patron/521181.json
Part of #86 
This only lists the fines and doesn't get history or deal w/ displaying accruing fines (not sure if this should be spun out into separate tickets or not).
There also may be some data missing (primarily `borrowed on` date and `assumed lost fee`) that didn't seem to be coming back in the response.  Happy to pair on that, or ship this and split that out into a separate ticket as well.
> Update fines page to use flex-box layout/proper headers/etc.

- app/assets/stylesheets/modules/page-section.scss
- app/assets/stylesheets/modules/record.scss
Moves list row padding/margin removal to be generic to page-sections so it applies everywhere.
> Fix some minor alignment issues in the "table" header/columns

- app/views/shared/_header_navbar.html.erb
> Move the modal out of the navbar so it doesn't get the navbar-specific css

- app/models/checkout.rb
- app/views/checkouts/_checkout.html.erb
- spec/models/checkout_spec.rb
Part of #120 
This PR adds logic to calculate days until an item is due. This is added to checkout details, but hidden if the item is overdue.
> Add days remaining until due date

- app/models/fine.rb
- app/views/fines/_fine.html.erb
- spec/models/fine_spec.rb
It looks like @jgreben ran into an exception in -dev because of a fine without an associated item. I'm not sure if this is a real use case or just some bad test data, but guarding against it is easy enough, so 🤷‍♂
> Guard against fines without an associated item; fixes #151

- app/helpers/application_helper.rb
- app/helpers/checkouts_helper.rb
- app/models/checkout.rb
- app/services/symphony_client.rb
- app/views/checkouts/_checkout.html.erb
- app/views/checkouts/index.html.erb
- config/locales/en.yml
- spec/features/checkouts_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/checkouts_helper_spec.rb
- spec/models/checkout_spec.rb
Closes #142 
Also updates the Remaining data to use `distance_of_time_in_words` (so we don't get `0 days`)
> Make short term loan's due date show the time instead of just date

- spec/helpers/checkouts_helper_spec.rb
This was failing the build when run on hours that were single digit `7` but passed for double digit `12`
> Make test more flexible to handle single and double digit hours

- app/helpers/fines_helper.rb
- app/models/fine.rb
- app/views/fines/_fine.html.erb
- spec/helpers/fines_helper_spec.rb
- spec/models/fine_spec.rb
Part of #130 
This PR adds `Days overdue` and the `{Type} Fee` data.
> Add more details to the Fines page

- app/models/fine.rb
- app/views/fines/_fine.html.erb
- spec/features/fines_spec.rb
- spec/models/fine_spec.rb
It wasn't really correct and we may not have the data to accurately show the user how many days they were fined for.
Also updates the label for Billed on to reflect the labels & content doc.
I believe this closes #130 as the data there now reflects the labels & content doc (but not necessarily the original issue)
>  Remove days overdue from Fine.

- app/assets/stylesheets/modules/header_navbar.scss
- app/assets/stylesheets/modules/navigation.scss
- app/assets/stylesheets/modules/top_navbar.scss
Nav hover:
Contact links:
Header nav:
> Update nav link styling; fixes #194

- app/helpers/application_helper.rb
- app/views/checkouts/_checkout.html.erb
- app/views/fines/_fine.html.erb
- app/views/requests/_request.html.erb
- spec/helpers/application_helper_spec.rb
> Update layout of expanded details content; fixes #192

- app/views/summaries/index.html.erb
- spec/features/summaries_spec.rb
I'm assuming the privileges expiration date is only set in Symphony for the users we want to show this information.
>  Add privileges expire information to the summary; fixes #216

- .rubocop.yml
- app/models/patron.rb
- app/views/checkouts/index.html.erb
- app/views/summaries/index.html.erb
- spec/models/patron_spec.rb
- spec/views/checkouts/index.html.erb_spec.rb
> Add information about the number of checkouts remaining to the summary + checkouts page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/mixins.scss
- app/assets/stylesheets/modules/clamp.scss
- app/assets/stylesheets/modules/record.scss
- app/views/checkouts/_checkout.html.erb
- app/views/fines/_fine.html.erb
- app/views/fines/_payment.html.erb
- app/views/requests/_request.html.erb
Closes #217 
Note that the call number is two lines already, so we have space for two lines of the author name if needed.
> Truncate authors to one line

- app/models/checkout.rb
- app/models/fine.rb
- app/models/patron.rb
- app/models/request.rb
- app/views/checkouts/_checkout.html.erb
- app/views/fines/_fine.html.erb
- app/views/requests/_request.html.erb
- spec/features/proxy_user_spec.rb
- spec/models/patron_spec.rb
Part of #159 
Displays borrower name on group tab:
Does not display borrower name for self:
> Adds borrower name in the group content.

- app/views/shared/_navigation.html.erb
- spec/features/navigation_spec.rb
After selecting a groups tab, navigation links should keep the user in the group context.
> Navigation tabs should 'remember' if you're in a group context or not

- app/controllers/application_controller.rb
- app/controllers/checkouts_controller.rb
- app/controllers/fines_controller.rb
- app/controllers/requests_controller.rb
- app/models/group.rb
- app/models/patron.rb
- app/views/checkouts/_checkout.html.erb
- app/views/checkouts/index.html.erb
- app/views/fines/_fine.html.erb
- app/views/group/_group.html.erb
- app/views/patron/_patron.html.erb
- app/views/requests/_request.html.erb
- app/views/shared/_navigation.html.erb
- app/views/summaries/_summary.html.erb
- app/views/summaries/index.html.erb
- spec/controllers/application_controller_spec.rb
- spec/controllers/checkouts_controller_spec.rb
- spec/controllers/fines_controller_spec.rb
- spec/controllers/requests_controller_spec.rb
- spec/models/group_spec.rb
- spec/models/patron_spec.rb
- spec/views/checkouts/index.html.erb_spec.rb
- spec/views/summaries/index.html.erb_spec.rb
This got a little out of hand with a small refactor to make it easier to show information for the group, but took care of a couple things:
- fixes #239 by showing patron types for sponsors, proxies, and groups
- displaying group/user specific information in the navigation and summary
- DRY'ed up some of the "are we talking about a patron or a group" logic
> Improvements for sponsor, proxy and group display

- app/assets/javascripts/modal.js
- app/controllers/contact_forms_controller.rb
- app/helpers/application_helper.rb
- app/helpers/contact_forms_helper.rb
- app/mailers/contact_mailer.rb
- app/views/contact_forms/new.html.erb
- app/views/fines/_fine.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_modal.html.erb
- app/views/shared/contact_forms/_form.html.erb
- config/application.rb
- spec/controllers/contact_forms_controller_spec.rb
- spec/features/contact_form_spec.rb
- spec/features/fines_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/contact_forms_helper_spec.rb
- spec/mailers/contact_mailer_spec.rb
Fixes #37 
The JavaScript is mostly ported from Blacklight and how it does its nice configurable modals. This will enable #242 very easily
> Implement custom contact form

- app/assets/stylesheets/base.scss
I noticed this while implementing #260. Seems like it would be a more useful cursor.
> Add pointer cursor for sortable titles

- app/views/patron/_patron.html.erb
- spec/views/summaries/index.html.erb_spec.rb
This could have been implemented using the existing `shibboleth?` method, but would not work in local development. I've implemented the `library_id_user` to reduce developer confusion.
We may also want to adjust markup here (column lengths) but thought that might want to be deferred once we get all of the information needed here.
> Add eResource access message for library_id logged in users, fixes #214

- .rubocop.yml
- app/assets/stylesheets/modules/checkouts.scss
- app/assets/stylesheets/modules/icons.scss
- app/controllers/requests_controller.rb
- app/helpers/requests_helper.rb
- app/models/library_location.rb
- app/models/request.rb
- app/services/symphony_client.rb
- app/views/checkouts/_checkout.html.erb
- app/views/requests/_request.html.erb
- app/views/requests/edit.html.erb
- config/application.rb
- config/locales/en.yml
- spec/controllers/requests_controller_spec.rb
- spec/features/requests_spec.rb
- spec/helpers/requests_helper_spec.rb
- spec/models/library_location_spec.rb
- spec/support/fake_symphony.rb
> Canceling a single request

- app/assets/stylesheets/nojs.scss
- app/views/layouts/application.html.erb
- config/initializers/assets.rb
Fixes #283 
Loads a special stylesheet for nojs views (showing the collapses that aren't the feedback form)
> Show the collapses when javascript is not available

- Gemfile
- Gemfile.lock
- app/models/borrow_direct_requests.rb
- app/models/patron.rb
- app/views/requests/_borrow_direct_request.html.erb
- config/initializers/borrow_direct.rb
- config/settings.yml
- spec/models/borrow_direct_requests_spec.rb
- spec/models/group_spec.rb
- spec/models/patron_spec.rb
- spec/spec_helper.rb
> Add initial support for displaying active BorrowDirect requests in requests tab

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/feedback_forms_controller.rb
- app/views/shared/feedback_forms/_form.html.erb
- config/initializers/recaptcha.rb
- config/settings.yml
- spec/controllers/feedback_forms_controller_spec.rb
- spec/features/feedback_form_spec.rb
Fixes #42 
To test locally, make sure to add the keys to your local settings.
Adapted from: https://github.com/sul-dlss/SearchWorks/pull/2009
In conjunction with:
https://github.com/sul-dlss/shared_configs/pull/991
https://github.com/sul-dlss/shared_configs/pull/992
https://github.com/sul-dlss/shared_configs/pull/993
> Adds reCAPTCHA challenge to feedback form for non-logged in users

- app/views/patron/_patron.html.erb
`Borrow limit` only applies to fee borrowers. Now that we fee borrowers have their own patron info partial (#318), we should be able to remove this from generic patron logic. See ["Patron info" in the content and labels doc.](https://docs.google.com/document/d/103F_NJJsBx-Bb7Op6nHGmwqylVcl5EvI7V67-PLa4Ho/edit#heading=h.v49m8d1k6ytw)
> Remove borrow limit from generic patron

- app/controllers/application_controller.rb
- app/controllers/checkouts_controller.rb
- app/controllers/fines_controller.rb
- app/controllers/requests_controller.rb
- app/helpers/application_helper.rb
- app/models/payment.rb
- app/models/request.rb
- app/services/symphony_client.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/summaries_controller_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/models/payment_spec.rb
- spec/models/request_spec.rb
- spec/services/symphony_client_spec.rb
There's also some fixes for some real-world power-user problems in this branch so at least the app doesn't break on it. More analysis might be needed for these.
- fee payments can be multivalued (=> #317)
- sometimes requests don't have items associated (=> #313)
This improves the summary page load from 17s => 1s, although the checkouts page itself is still very slow.
> Improve performance for users with tons of checkouts

- app/controllers/payments_controller.rb
- app/helpers/payments_helper.rb
- app/models/fine.rb
- app/views/fines/index.html.erb
- app/views/shared/_navigation.html.erb
- config/locales/en.yml
- config/routes.rb
- config/settings/test.yml
- spec/controllers/fines_controller_spec.rb
- spec/controllers/payments_controller_spec.rb
- spec/features/fines_spec.rb
- spec/helpers/payments_helper_spec.rb
- spec/models/fine_spec.rb
Payment amount with payment button:
After going to CyberSource and clicking Cancel button:
After successful payment and clicking Return to Website:
After a moment when they navigate away from the Fines tab or click on the Fines tab again, Symphony will have processed the payment, the payment will appear in the payment history, and the payment pending status will disappear.
> Payment workflow

- app/assets/stylesheets/modules/checkouts.scss
- app/assets/stylesheets/modules/clamp.scss
- app/views/checkouts/_checkout.html.erb
- app/views/checkouts/_recalled.html.erb
- app/views/checkouts/index.html.erb
- app/views/fines/_fine.html.erb
- app/views/fines/_payment.html.erb
- app/views/fines/index.html.erb
- app/views/requests/_borrow_direct_request.html.erb
- app/views/requests/_request.html.erb
- app/views/requests/index.html.erb
Fixes #330
The main changes here:
- Only do the renewable-indicator negative margin when on lg and above screens
- Move everything from 2 -> 3 line truncation
- Modify how checkouts stack in md and below sizes
I paired with @jvine on the final details.
> Implement breakpoint truncation changes fixes #330

- app/models/checkout.rb
- app/models/fine.rb
- app/models/patron.rb
- app/views/checkouts/_checkout.html.erb
- app/views/checkouts/_renew_all_button.html.erb
- app/views/checkouts/index.html.erb
- app/views/fines/_pay_all_button.html.erb
- app/views/fines/index.html.erb
- app/views/requests/_request.html.erb
- app/views/summaries/_summary.html.erb
- spec/features/summaries_spec.rb
- spec/models/patron_spec.rb
- spec/support/fixtures/patron/521181.json
- spec/support/fixtures/patron/521182.json
- spec/views/checkouts/_renew_all_button.html.erb_spec.rb
- spec/views/fines/_pay_all_button.html.erb_spec.rb
- spec/views/summaries/index.html.erb_spec.rb
For a blocked user:
Fixes #95 
Fixes #294 
Fixes #295 
Disabled button styling spun out to #360
> Add checks for various patron abilities

- app/views/shared/contact_forms/_form.html.erb
> Add btn btn-link classes so that cancel button gets spaced consistently

- README.md
- lib/tasks/fixtures.rake
Also adds a handy rake task for doing so.
Fixes #364
> Add information about fixture users and how to create them

- app/assets/stylesheets/base.scss
> Add a disabled styles to all disabled w/ the disabled attribute

- app/views/fines/index.html.erb
Part of #402 
A temporary solution to the fact that sponsors cannot pay for their proxys' fines. Further work in Symphony cgi-script is required to allow these types of payments.
> Group fine payments

- app/views/fines/_fine.html.erb
> Add empty placeholders for fines with no bib record

- app/assets/javascripts/analytics.js
- app/views/fines/_pay_all_button.html.erb
> Add fine payment analytics events

- app/views/fines/index.html.erb
- spec/features/proxy_user_spec.rb
Closes #388
Proxy23 can see Proxy21's fines.
Proxy23 cannot see Proxy21's fines, does not have a pay button, and gets a notification.
> Does not render the fines table when viewing other proxies fines

- app/views/checkouts/_checkout.html.erb
- app/views/requests/_request.html.erb
> Add some labels to checkout and request dates for the mobile view only; fixes #418

- app/services/symphony_client.rb
- config/settings.yml
- spec/services/symphony_client_spec.rb
Fixes #391 
This can be manually tested by putting in a request on searchworks-morison for a title. With the current app, the item will not be renewable. With this commit, the item will be renewed (after receiving the initial rejecting and following up with a prompt override)
> Override renewal errors for title-level holds

- app/models/request.rb
- spec/models/request_spec.rb
Some holds, like title-level for things on-order return nil values for queueLength and queuePosition:
This makes the waitlist position "Unknown" for these situations:
> Requests for on-order items do not have queue length or position.

- .rubocop.yml
- app/models/checkout.rb
- app/models/request.rb
- app/views/checkouts/_checkout.html.erb
- app/views/requests/_request.html.erb
- config/settings.yml
- spec/models/checkout_spec.rb
- spec/models/request_spec.rb
- spec/views/checkouts/_checkout.html.erb_spec.rb
- spec/views/requests/_request.html.erb_spec.rb
>  Show 'Source: BorrowDirect' for requests (in addition to checkouts)

- .rubocop.yml
- app/models/checkout.rb
- app/models/concerns/bib_record.rb
- app/models/fine.rb
- app/models/request.rb
This pulls over all the accessors we made for `bib`/`item`/`call` data into a common mixin that is nice and defensive about missing data (in a consistent way across checkouts, requests, and fines).
> Extract a BibRecord mixin

- app/views/payments/index.html.erb
- spec/features/fines_spec.rb
- spec/features/payments_spec.rb
Fixes #436 
If a user has no fines, stop the loading spinner and returns the message:
> Stop loading spinner if no payment history is available

- spec/features/payments_spec.rb
> Add a test for users with no payment history

- app/views/requests/_borrow_direct_request.html.erb
> Update borrowdirect requests using the DOM structure for other requests

- app/controllers/application_controller.rb
- config/settings.yml
- spec/features/internal_flash_message_spec.rb
```
internal_pages_flash_message_html: |-
<p>As of Monday, 9/9/19, we are having an issue with renewing materials due on 9/23/19.  Renewals will be available on Tuesday, 9/10/19.</p>
internal_pages_flash_message_config:
- summaries
- checkouts
```
🎃 squash these please
> Add a configurable flash message for internal pages

- app/controllers/application_controller.rb
- config/settings.yml
Renewals issue has been resolved. I also added a lil' check for whether the string is `present?` to account for a lil' edge case.
> Unset flash msg

- app/models/checkout.rb
- spec/models/checkout_spec.rb
Fixes #481 
Checks if `fields['library']` is nil and returns empty string
```
ActionView::Template::Error: undefined method `[]' for nil:NilClass
checkout.rb 111 library(...)
[PROJECT_ROOT]/app/models/checkout.rb:111:in `library'
109 
110   def library
111     code = fields['library']['key']
112     return Settings.BORROW_DIRECT_CODE if from_borrow_direct?
```
> Add check for nil library so checkouts list can display

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/global-alert.scss
- app/views/layouts/application.html.erb
- app/views/shared/_global_alert.html.erb
- config/settings.yml
Fixes #505
We'll want to flip the switch in shared configs on the Wednesday before break.
❗️ Note that this global message is _separate_ from the existing `home_page_flash_message_html` and the `internal_pages_flash_message_html`. 
```YAML
internal_pages_flash_message_html: a requests-specific message
internal_pages_flash_message_config:
- requests
GLOBAL_ALERT: <%= true %>
global_flash_message_html: The Stanford Libraries will be operating on a reduced schedule during the Stanford Winter Closure period (December 21, 2019 - January 5, 2020).<br /><a href="https://library.stanford.edu/winterclosure">More information about schedules and affected services</a>
```
```YAML
home_page_flash_message_html: a blizzard in California?!
GLOBAL_ALERT: <%= true %>
global_flash_message_html: The Stanford …
```
> Add a configurable global alert for winter closure

- app/models/patron.rb
- spec/features/requests_spec.rb
- spec/features/summaries_spec.rb
MEDIA-MTXT items will be paged, but their pickup library will be GREEN not MEDIA-MTXT
> Only show green schedule buttons when the pickup library is GREEN

- app/controllers/renewals_controller.rb
- app/models/checkout.rb
- app/services/symphony_client.rb
- spec/controllers/renewals_controller_spec.rb
- spec/models/checkout_spec.rb
- spec/services/symphony_client_spec.rb
Fixes #649.
This PR adds a new condition to stop patrons from renewing items that are marked as `NORENEW`. It also adds additional authorization for this condition within the application because Symphony won't enforce it for us.
> Remove renewal eligibility for items with Item Cat5 of "NORENEW" 

- config/deploy.rb
This is something we like to do with the libsys ruby aps so we can deploy branches for testing. It also helps with the bug that the master branch is still queried for the tar archive.
> Ask which branch to deploy

- app/services/symphony_client.rb
- config/settings.yml
Fixes #678 
Associated shared configs PRs must be merged before deploying this.
> Use public client ID for patron pin reset requests

- app/models/borrow_direct_reshare_requests.rb
- app/models/patron.rb
- app/services/borrow_direct_reshare_client.rb
- app/views/requests/_borrow_direct_request.html.erb
- config/settings.yml
- spec/models/borrow_direct_reshare_requests_spec.rb
- spec/services/borrow_direct_reshare_client_spec.rb
BorrowDirect is changing back-end providers. This adds a client class for making requests to BorrowDirect reshare's new folio based system, a new request model to make the request for a patron's BorrowDirect requests, and wraps the response JSON in a class to mimic the Symphony request object behavior.
Closes #757 
Looks like (no design change from current implementation):
> Implement BorrowDirect ReShare requests list for patron.

- .github/workflows/ruby.yml
Addresses the following github actions warnings:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2
> 
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> 
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output- …
> Set actions/checkout to version 3

- .github/workflows/ruby.yml
> Stop testing on old rubies

- Gemfile
- Gemfile.lock
- app/services/cql_query.rb
- app/services/folio_client.rb
- spec/services/cql_query_spec.rb
> Add FolioClient for renewing items and canceling holds

- .rubocop.yml
This eliminates a warning when running rubocop:
```
The following RuboCop extension libraries are installed but not loaded in config:
* rubocop-capybara
```
> Add rubocop-capybara to the require

- app/assets/stylesheets/deja-vu-font.scss
The former is a sprockets method, which we are no longer using.
Fixes #814
> Replace font-url with url

- app/models/folio/patron.rb
#811 and #812 happened concurrently and we missed some updates needed in the FOLIO classes.
> Update Folio::Patron to use the new borrowdirect constructor signatures

- app/assets/javascripts/cable.js
The library has been renamed upstream and it currently issues a deprecation on the console when using the old name
> Rename action_cable to actioncable

- app/models/folio/checkout.rb
Seems like since we're doing math to arrive at the renewals remaining count that it could be less than 0 under some conditions? Such as if there's a way for staff to override?
> Handle case where renewals remaining is less than 0

- config/initializers/okcomputer.rb
This prevents Honeybadger errors: https://app.honeybadger.io/projects/62116/faults/68862673
> Remove okcomputer check for symphony when not using symphony

- app/controllers/reset_pins_controller.rb
- app/mailers/reset_pins_mailer.rb
- app/services/folio_client.rb
- app/services/symphony_client.rb
- app/views/reset_pins_mailer/reset_pin.html.erb
- app/views/reset_pins_mailer/reset_pin.text.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/locales/en.yml
- config/settings.yml
- spec/controllers/reset_pins_controller_spec.rb
- spec/features/reset_pin_spec.rb
- spec/mailers/previews/reset_pins_preview.rb
- spec/mailers/reset_pins_mailer_spec.rb
Closes #739
This implements a user flow where the patron can request that an
email be sent to them that includes a token, which can be used
to reset their PIN. Symphony generates this email, but for FOLIO
we need to generate and send it ourselves, including the token.
You can view a preview of what the email looks like by visiting
/rails/mailers/reset_pins/reset_pin. It's designed to look the
same as the ones Symphony generates currently.
> Support resetting patron PINs using FOLIO APIs

- Gemfile
- Gemfile.lock
- app/models/folio/checkout.rb
- app/models/folio/loan_policy.rb
- app/services/folio_graphql_client.rb
- spec/models/folio/loan_policy_spec.rb
This new class suggests some refactoring -- moving loan policy related methods from Folio::Checkout to Folio::LoanPolicy, but I thought it would be better to save that for another PR.
> Add Folio::LoanPolicy class to wrap renewal logic

- app/models/folio/checkout.rb
> Remove unused circulation_rule method

- app/models/folio/checkout.rb
- app/models/folio/request.rb
Private method `item_type` had been used by Symphony implementation to get ILL info. This is no longer needed for the FOLIO implementation.
> Remove unused private methods

- app/models/folio/fine.rb
- app/services/folio_graphql_client.rb
- app/views/fines/_fine.html.erb
- spec/models/folio/fine_spec.rb
- spec/views/fines/index.html.erb_spec.rb
> Display fines using FOLIO model

- config/application.rb
- config/environments/production.rb
- config/environments/test.rb
- Set the SameSite attribute to None for authentication cookie
- Force SSL when RAILS_ENV=production
This fixes the existing behavior where the user is signed out and redirected to the root after making a payment, because once we go out to Cybersource we lose our authentication cookie.
> Support retaining our auth cookie during payment

- .rubocop.yml
- config/environments/development.rb
See #887; this just applies the same fix we currently use in test
to the dev server so that authentication, etc. will work in
local dev.
> Set SameSite cookie attribute to 'Lax' in development

- README.md
- app/controllers/payments_controller.rb
- app/models/cybersource/payment_request.rb
- app/models/cybersource/payment_response.rb
- app/services/cybersource/security.rb
- app/services/folio_client.rb
- app/services/symphony_client.rb
- app/views/fines/_pay_all_button.html.erb
- app/views/payments/cybersource_form.html.erb
- config/locales/en.yml
- config/settings.yml
- spec/controllers/payments_controller_spec.rb
- spec/models/cybersource/payment_request_spec.rb
- spec/models/cybersource/payment_response_spec.rb
This PR supersedes (and was based on) #878. It closes #883.
See the changes to the README for some background on the payment process.
Before this PR, the process of sending information to and from Cybersource via POST was done by some PHP scripts that are located on the Symphony VMs. After the transaction with Cybersource, the PHP scripts in turn called a perl script on the same Symphony VM called `transactionPost.pl` which used some of Symphony's locally-available scripts (not web services or APIs) to actually mark the fine as paid.
After this PR, the code that sends users to and from Cybersource has moved into MyLibrary as ruby (it takes essentially the same approach of rendering an interstitial form). After the transaction is completed, MyLibrary calls the `transactionPost.pl` script …
> Handle Cybersource payments without redirecting to Symphony

- app/views/sessions/index.html.erb
Previously it looked like this:
> Don't show the login banner if you can't login

- app/controllers/requests_controller.rb
- app/helpers/application_helper.rb
- app/helpers/requests_helper.rb
- app/models/borrow_direct_reshare_requests.rb
- app/models/folio/request.rb
- app/models/folio/service_point.rb
- app/services/folio_client.rb
- app/services/folio_graphql_client.rb
- app/services/symphony_client.rb
- app/views/requests/edit.html.erb
- config/settings/test.yml
- spec/controllers/requests_controller_spec.rb
- spec/factories/service_points.rb
- spec/features/requests_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/requests_helper_spec.rb
- spec/models/borrow_direct_reshare_requests_spec.rb
- spec/models/folio/service_point_spec.rb
- spec/views/requests/_request.html.erb_spec.rb
The service point model code started based on the same model from `sul-requests`
Closes #875
> Use service points for FOLIO request options

- Gemfile
- Gemfile.lock
- config/initializers/okcomputer.rb
the `SymphonyDbClient` implementation appears defensively coded in case the gem isn't available, so it can wait until we clean up all the Symphony stuff 🤷‍♂️ 
Part of #913
> Remove oci8 gem

- app/models/folio/patron.rb
Patron keys (ids) are stored on the patron object returned from
graphQL, not the user.
Fixes #925
> Look for the patron id in the right place in the data

- app/models/folio/checkout.rb
- spec/models/folio/checkout_spec.rb
Fixes many of the `FolioClient::IlsError: Renew request` errors: https://app.honeybadger.io/projects/62116/faults/99827607
Partially addresses #930
> Check item status to determine if it is lost

- app/controllers/requests_controller.rb
- app/services/folio_client.rb
This fixes #957. There are still some Symphony-isms here, but refactoring the tests for FOLIO is somewhat involved and I'd like to consider that work separately from getting this feature working. The work to update the tests and start to remove Symphony-isms is captured by #956.
> Get "not needed after" working in FOLIO

- app/assets/stylesheets/modules/global-alert.scss
- app/assets/stylesheets/sul-variables.scss
- app/views/reset_pins/index.html.erb
- app/views/sessions/index.html.erb
- Small updates to the global-alert style
- Extends global-alert to a "local-alert" style
- Local PIN alerts added inline to `request_pins` and `sessions` views. (To be deleted when the PIN alert is no longer applicable.)
- Adds [SU Web Interactive Colors](https://identity.stanford.edu/design-elements/color/web/) (WCAG AA compliant)
- Swaps the "Request/Reset" order in the `request_pins` heading for consistency
- The global PIN alert should be deleted (see [this global_alerts PR](https://github.com/sul-dlss/global_alerts/pull/60))
Issue: #943
Tested: localhost and rake
> Update PIN alerts

- app/controllers/renewals_controller.rb
- config/locales/en.yml
- spec/controllers/renewals_controller_spec.rb
Fixes https://github.com/sul-dlss/mylibrary/issues/963
There's probably a better long term solution where we wire up turbo/hotwire to show renewal response information rather than relying on flash. However, we're seeing a fair number of these errors and I'd like to get this fix out and defer other improvements to separate issues https://github.com/sul-dlss/mylibrary/issues/465 and https://github.com/sul-dlss/mylibrary/issues/466.
> Reduce size of bulk renewal flash message to avoid CookieOverflow

- spec/controllers/requests_controller_spec.rb
Noticed a few issues with these tests as I was working on something else.
- In FOLIO resource and id are set to the same value
- There were various references to "checkout_path" that were likely copy pasta that should be "requests_path".
- Some references to "item" are more accurately "request" in FOLIO.
> Fix test descriptions and params

- app/controllers/payments_controller.rb
- app/models/cybersource/payment_request.rb
- app/models/cybersource/payment_response.rb
- app/models/folio/account.rb
- app/services/folio_client.rb
- app/views/fines/_pay_all_button.html.erb
- spec/controllers/fines_controller_spec.rb
- spec/controllers/payments_controller_spec.rb
- spec/models/cybersource/payment_request_spec.rb
- spec/models/cybersource/payment_response_spec.rb
- spec/views/fines/_pay_all_button.html.erb_spec.rb
- spec/views/fines/index.html.erb_spec.rb
- spec/views/summaries/summary.html.erb_spec.rb
Closes #971 
- Send user UUIDs to CyberSource instead of a session ID
- Clean up Symphony-specific fine payment code and tests
> Send user UUIDs to CyberSource for payment tracking

- .github/workflows/ruby.yml
All environments are deployed on 3.2 now.
> Drop Ruby 3.1 builds

- spec/features/checkouts_spec.rb
Maybe there's a better way to deal with this? But this particular test has been very unreliable lately.
> Let Capybara wait up to 10 seconds for flaky JS test

- app/models/concerns/folio/folio_record.rb
We only care about whether Folio::Checkout objects are lost and it's defined correctly for FOLIO there.
> Remove unused lost? method on Folio::FolioRecord

- app/views/requests/index.html.erb
Closes #997 
What this pull request does:
Delete the two links in requests index.html.erb that pointed to https://sulils.stanford.edu/
> removing interlibrary loan and scan links on requests page

- app/models/illiad_requests.rb
- spec/models/illiad_requests_spec.rb
Closes #1001 .
What this pull request does:
Check for transaction status to belong to a specific set (which according to the spreadsheet in the linked issue indicates that that request should not be displayed).
If the transaction status in this set, the transaction is inactive.
When illiad requests are returned for the patron, inactive requests will not be included.
> not displaying inactive illiad requests based on transaction status

- app/models/concerns/folio/folio_record.rb
- app/views/checkouts/_checkout.json.jbuilder
- spec/controllers/renewals_controller_spec.rb
- spec/features/renew_item_spec.rb
- spec/models/concerns/folio/folio_record.rb
- spec/views/checkouts/_checkout.html.erb_spec.rb
- spec/views/requests/edit.html.erb_spec.rb
Folio only requires the item id for renewals whereas Symphony required the bib record id (instance id). This is no longer used or needed.
> Remove FolioRecord#resource method that was added for parity with Symphony; no longer used.

- app/controllers/application_controller.rb
Was added here: https://github.com/sul-dlss/mylibrary/commit/64cf61e549f3f316d831809bf64d9f7eb29a954e
But we're probably no longer worried about old sessions with Symphony patron keys.
> Remove code that checks for old sessions with Symphony patron keys

- app/models/folio/group.rb
- app/models/folio/patron.rb
- app/views/fines/index.html.erb
- app/views/summaries/_summary.html.erb
In FOLIO fines on items borrowed by a proxy are associated with the sponsor's individual account. We never display these fines when the proxy views their group activity and the fines display on the "Self" tab for the sponsor. None of the conditions in the related fine/summary views that check for both fines and the group parameter being set will ever be true. These conditions existed for Symphony. We can now remove the conditionals and the Symphony-only displays.
> Remove fee/fine conditions for proxy groups that do not apply in FOLIO

- app/views/reset_pins/index.html.erb
- app/views/sessions/index.html.erb
- app/views/shared/_unavailable.html.erb
- config/settings.yml
> Remove migration messaging

- app/assets/stylesheets/base.scss
This is causing the rest of the page to shift down 1px when hovering over the nav bar links. Presumably this was addressed upstream in bootstrap at some point and this work-around is no longer necessary.
> Remove nav-link border styling

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/base.scss
- app/assets/stylesheets/modules/global-alert.scss
- app/views/feedback_forms/new.html.erb
- app/views/layouts/application.html.erb
- app/views/payments/index.html.erb
- app/views/sessions/index.html.erb
- app/views/shared/_global_footer.html.erb
- app/views/shared/_sul_footer.html.erb
- app/views/shared/_unavailable.html.erb
- app/views/shared/contact_forms/_form.html.erb
- app/views/shared/feedback_forms/_form.html.erb
- spec/features/axe_spec.rb
- spec/features/contact_form_spec.rb
cloeses #951 
Updates in this PR, screenshots attached:
- pages without h1 had h1 elements added. Some h2 elements got migrated to h1
- links that were part of text elements got underlines added
- fix alert-info link text color to match alert info
- move global footer into footer (this should not change anything outside structure)
- remove roles contentinfo and form
- add axe spec
Homepage
Summaries
Checkout
Requests
Fines
Payments
Contact
Feedback
Reset pin
Change pin
Unavailable
> add axe spec, update accessibility so tests pass

- config/initializers/okcomputer.rb
fixes "No matching check (`OkComputer::Registry::CheckNotFound`)"
> Allow the rails console to start even if Folio isn't configured

- app/controllers/reset_pins_controller.rb
- app/controllers/sessions_controller.rb
- app/services/folio_client.rb
- app/views/reset_pins/change_form.html.erb
- app/views/reset_pins/index.html.erb
- app/views/sessions/form.html.erb
- config/initializers/warden.rb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/reset_pins_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
- spec/features/reset_pin_spec.rb
Connects to sul-dlss/SearchWorks#3773
This commit helps us move the access portfolio beyond using library barcode numbers, leaning instead on the university-assigned and -managed "university ID."
> Rename "Library ID" to "University ID"

- app/views/checkouts/_checkout.html.erb
- app/views/checkouts/_renew_all_button.html.erb
- config/locales/en.yml
- spec/views/checkouts/_renew_all_button.html.erb_spec.rb
Part of #1083 -- prevents duplicate POST requests when renewing items takes a long time.
This takes advantage of turbo to display a "Renewing..." message after either the all or single renewal buttons is clicked. The renew all link is changed to a form so this will work.
Renew button before submitting:
Renew button after submitting:
> Set a data-turbo-submits-with message when renewing

- spec/features/axe_spec.rb
> update axe tests

- .github/workflows/ruby.yml
This might fix the test environment setup failure here: https://github.com/sul-dlss/mylibrary/pull/1146
```
The installation path is insecure. Bundler cannot continue.
/opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/gems/3.2.0/gems is world-writable
(without sticky bit).
Bundler cannot safely replace gems in world-writeable directories due to
potential vulnerabilities.
Please change the permissions of this directory or choose a different install
path.
Error: Process completed with exit code 38.
```
> Set bundle path

- config/initializers/okcomputer.rb
Adds optional check for borrow direct service. Check will fail if we're unable to get a token from borrow direct.
> Add okcomputer check for borrow direct service

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/component-library-overrides.css
- app/assets/stylesheets/modules/navigation.scss
- app/assets/stylesheets/modules/sul-footer.scss
- app/assets/stylesheets/modules/top_navbar.scss
- app/assets/stylesheets/su-identity-overrides.scss
- app/assets/stylesheets/sul-variables.scss
- app/views/shared/_sul_footer.html.erb
- app/views/shared/_top_navbar.html.erb
Background: 
We need to move the MyLibrary logo to the new Stanford Libraries logo.  The objective is NOT to redo the header and footer in their entirety, as the next SearchWorks related workcycle may look into redoing the header/footer in its entirety.
I based this work on the component library and looking at changes in this VT Arclight PR: https://github.com/sul-dlss/vt-arclight/commit/79cd4960ed02d0413ecb34332cbde2c5feff7d57, 
What this pull request does:
- Uses the new logo and related classes for the header
- Changes the footer portion to correspond to a darker shade. This was a request based on the look and feel for the footer in https://library.stanford.edu/all . 
- Use the new logo in the footer. 
- Changes the links in that footer section to be white.
**Before Header**
**After …
> Include the new logo and change the color of the footer banner logo portion to a darker color

- Gemfile
- Gemfile.lock
We're getting jquery from yarn/jsbundling-rails
> Remove jquery-rails

- app/helpers/requests_helper.rb
- app/models/folio/group.rb
- app/models/folio/patron.rb
- app/models/folio/request.rb
- app/models/folio/service_point.rb
- app/views/requests/edit.html.erb
- config/settings.yml
- spec/helpers/requests_helper_spec.rb
- spec/views/requests/edit.html.erb_spec.rb
Fixes #1234 
We're not currently validating and enforcing the pickup service point (for this or location-restricted pages), but at least we won't show patrons service points that they shouldn't choose. 
If the patron already has an open request that's delivered to some restricted service point, it's probably because the patron talked to library staff and negotiated access (and library staff placed the request for them). In that case, we get to leave the service point (but we shouldn't offer it as an option otherwise..)
> Don't show patrons places they can't pick up items because of their patron group.
